version: 2.1

orbs: 
  soos: soos-io/dast@1.0.1

workflows:
  main:
    jobs:
      - soos/analysis_run_and_wait:
          client_id: ${SOOS_CLIENT_ID}
          api_key: ${SOOS_API_KEY}
          project_name: "selene-circleci-dast"
          api_base_url: 'https://qa-api.soos.io/api/'